#TODO: What is this line of code doing
name: Deploy

#TODO: What is this block of code doing
on:
    pull_request:
      branches:
        - main
        
#TODO: What is this block of code doing   
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Use Node.js 21.x
          uses: actions/setup-node@v1
          with:
            node-version: 21.x

        # Install dependencies
        - name: 🧰 Install Deps
          run: npm install

        # Run build
        - name: Run Build
          run: npm run build

        - name: Test
          run: |
            npm run test-component
            npm run test

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"